package com.phntechnolab.sales.util

object Constants
{
    const val BASE_URL = "https://www.phntechnology.info/phn_connect/"
//    const val DEV_URL = "https://www.phntechnology.info/newphn/"
    const val TEST_URL = "https://www.phntechnology.info/phn_career_test/"
    const val TEST_URL1 = "https://sales.paytmmoneey.com/"
//    const val TEST_URL1 = "http://127.0.0.1:8000/"
    const val DEV_URL = "https://www.phntechnology.info/phn_career/"
    const val WHATSAPP_URL = "https://api.whatsapp.com/send?phone=91"
    const val SHARED_PREF_FILE = "PREF_FILE"
    const val USER_ID = "user_id"
    const val USER_EXISTS = "user_exists"
    const val MOBILE_NUMBER = "mobile_Number_new"
    const val EMAIL_ADDRESS = "email_address"
    const val USER_ROLE = "user_role"
    const val SCTYPE = "type"
    const val SCHOOL = "School"
    const val COLLEGE = "College"
    const val JAP = "JAP" // Job Assistant Programme
    const val MOBILE_NUMBER_VERIFIED = "mono_verified"
    const val RANDOM_NUMBER = "random_number"
    const val REGISTER_PASS_INFO = "RegisterInfo"
    const val IS_REGISTERED = "IsRegistered"
    const val IS_USER_REGISTERED = "is_User_Registered"
    const val IS_USER_ALREADY_REGISTERED = "is_User_Already_Exists"
    const val ACTIVATION_CODE = "activation_code"
    const val TELE_CALLER = "tele_caller"
    const val NEXT_SCREEN = "next_screen"
    const val WELCOME_SCREEN = "welcome_Screen"
    const val WHATSAPP_SCREEN = "whatsapp_screen"
    const val APP_SCREEN = "app_Screen"
    const val LETSGETSTARTED_SCREEN = "lets_Get_Started_Screen"
    const val WEBINAR_SCREEN = "webinar_screen"
    const val REFER_COUNT = "refer_count"
    const val REGISTRATION_SCREEN = "registration_screen"
    const val VIEW_REFERRAL_REFRESH = "view_referral_refresh_screen"
    const val APP_DETAIL = "app_detail"
    const val PRODUCT_DETAIL = "product_detail"
    const val VIDEO_DETAIL = "video_detail"
    const val QUESTION_DETAIL = "question_detail"
    const val SAVE_PROFILE = "save_profile"
    const val SAVE_PROFILE_S = "save_profile_stud"
    const val FNAME_LNAME = "fname_lname"
    const val SAVE_DATA = "save_data"
    const val APP_DETAIL_REFERRAL = "app_detail_referral"
    const val APP_REFERRAL_DATA_PASS = "app_referral_pass"
    const val SAVE_NAME = "save_name"
    const val FIRST_NAME = "first_name"
    const val HOME_SCREEN = "home_screen"
    const val USER_NAME_GOOGLE_FORM = "user_name_google"
    const val FIREBASE_TOKEN = "firebase_token"
    const val JWT_TOKEN = "jwt_token"
    const val CHILD_DETAILS = "child_details"
    const val NO_OF_CHILD = "no_of_child"
    const val CGTYPE = "cgtype"
    const val APPEARED = "Appeared"
    const val PURSUING = "Pursuing"
    const val PASSOUT = "Passout"
    const val CPDETAILS = "sc_details"
    const val SDETAILS = "s_details"
    const val SHOP_DATA = "shop_details"
    const val PARENT = "Parent"
    const val PROFILE_DATA = "profile_data"
    const val WHATSAPP_TYPE = "whatsapp_type"
    const val TYPE_STUD = "whatsapp_type_stud"
    const val TYPE_COLLEGE = "whatsapp_type_college"
    const val TYPE_PASSOUT = "whatsapp_type_passout"
    const val DISTRICT = "district"
    const val USER_TYPE = "user_type"
    const val USER_TYPE_REG = "user_type_reg"
    const val SAVE_ROLE_REG = "save_role_reg"
    const val SAVE_PASSOUT_INTEREST = "save_passout_interest"
    const val LIVE_SESSION = "live_session"
    const val ALL_COURSES = "all_courses"
    const val COURSES_SEE_ALL_DATA = "see_all_data"
    const val IS_PARENT = "is_parent"
    const val TO_ADD_REFERRAL = "to_add_referral"
    const val FROM_APP_DETAIL = "from_app_detail"
    const val FROM_VIEW_REFERRAL = "from_view_referral"
    const val USER_REG = "reg_user"
    const val BUNDLE = "bundle"
    const val JOB_SEEKER = "job_seeker"
    const val SAVE_JOB_SEEKER_PROFILE = "save_job_seeker_profile"
    const val SAVE_PURSUING_PROFILE = "save_pursuing_profile"
    const val SAVE_PARENT_PROFILE = "save_parent_profile"
    const val ROBOTICS = "Robotics"
    const val STUDENT = "Student"
    const val WEBINAR = "Webinar"
    const val APP = "App"
    const val WELCOME = "Welcome"
    const val WHATSAPP = "WhatsApp"
    const val LETSGETSTARTED = "LetsGetStarted"
    const val REGISTRATION = "Registration"
    const val PAYTM_MONEY = "Paytm Money"
    const val ANGEL_BROKING = "Angel Broking"
    const val APPROVED = "Approved"
    const val TEXT = "Text"
    const val URL = "url"
    const val SUBTITLE = "subtitle"
    const val TITLE = "title"
    const val DESCRIPTION = "description"
    const val THUMBNIL = "thumbnil"
    const val NOTIFICATION_ID = "notificationId"
    const val VIDEO = "Video"
    const val PRIVACY_POLICY = "Privacy Policy"
    const val PHN_CAREER_WEB_REG = "phn_career_web_reg"
    const val TERMS_CONDITIONS = "Terms and Conditions"
    const val FAQ = "FAQ"
    const val TO_WEBVIEW = "To_WebView"
    const val FROM_APPLICATION = "from_application"
    const val TO_APP_DETAIL = "to_app_detail"
    const val FROM_HOME = "from_home"
    const val FROM_APPS = "from_apps"
    const val HANDLE_BACKSTACK = "handle_backstack"
    const val FROM_SCREEN_TO = "from_screen_to"


    // splash screen names

    const val SPLASH_TO_WELCOME = "Splash_to_welcome"
    const val SPLASH_TO_APPLICATION = "Splash_to_application"
    const val SPLASH_TO_WEBINAR = "Splash_to_webinar"
    const val SPLASH_TO_WHATSAPP_PERMISSION = "Splash_to_whatsapp_permission"
    const val SPLASH_TO_LOGIN = "Splash_to_login"
    const val SPLASH_TO_TELECALLER = "Splash_to_telecaller"
    const val SPLASH_TO_CHOOSE_ROLE = "Splash_to_choose_role"
    const val SPLASH_TO_INITIAL_REG = "Splash_to_initial_reg"
    const val SPLASH_TO_ONBOARDING = "Splash_to_onboarding"
    const val SPLASH_TO_REGISTRATION = "Splash_to_registration"
    const val SPLASH_TO_LETS_GET_STARTED = "Splash_to_lets_get_started"
    const val SPLASH_TO_ACTIVATION_CODE = "Splash_to_activation_code"
    const val APP_DATA = "app_data"
    const val COURSE_DETAIL_TO_VIDEO = "course_detail_to_video"
    const val FROM_COURSE_TO_DETAIL = "from_course_to_detail"
    const val WEBINAR_TYPE = "webinar"
    const val VIDEO_TO_QUIZ = "video_to_quiz"
    const val COURSE_ID = "course_id"
    const val COURSE_TITLE = "course_title"
    const val IS_FROM_DOWNLOAD = "is_from_download"
    const val SECTION_ID = "section_id"
    const val MOBILE_NUMBER_PARAM = "mobile_no"
    const val QUIZ_TIMER = "quiz_timer"

    const val KEY_PLAYER_POSITION = "player position"
    const val KEY_PLAYER_PLAY_WHEN_READY = "player ready position"

    // Analytics Log Event Name

    const val WELCOME_EVENT_NAME = "WelcomeScreen"
    const val ADD_REFERRAL_EVENT_NAME = "AddReferral"



    // Analytics Parameters Name
    const val USER_NAME = "UserName"
    const val USER_MOBILE_NUMBER= "MobileNumber"
    const val USER_ROLE_= "UserRole"


    const val ABOUT_US_LINK = "https://www.phntechnology.com/about"
    const val CONTACT_US_LINK = "https://www.phntechnology.com/contact"
    const val PRIVACY_POLICY_LINK = "https://www.phntechnology.info/phn_career_test/privacy&policy.html"
    const val TERMS_COND_LINK = "https://www.phntechnology.info/phn_career_test/terms&condition.html"
    const val FAQ_LINK = "https://www.phntechnology.info/new_phn_connect/faq.html"
    const val PHN_CAREER_REG_LINK = "https://career.phntechnology.com/"






}